### ISSUE TITLE
Thank you for good paper can i ask about Cluster Loss?

### ISSUE THREAD

**Issue by kang7734** [mzhaoshuai/CenterCLIP#1]
Hello, first of all, thank you for revealing a good Research.

I am conducting training on MSVD dataset and CLoss is continuously 0.0000. Does this not matter at all?

Also, I wonder what cluster_inter means.

Currently, we have only downloaded Data path and Data from the given file, and changed it to train=1 eval=0.

We are using batch_size=16 (single gpu) as 4 gpu.

Once again, thank you for sharing good research.

**Comment by mzhaoshuai** [comment]
Well, `CLoss` represents `cluser_loss` in https://github.com/mzhaoshuai/CenterCLIP/blob/886fe7342956f361c9c7b93f82d05c7ec5ed677b/modules/cluster/deepcluster.py#L153.
It is one of our attempts to use deep networks for clustering.
It does not work now.

`cluster_inter ` means clustering within the transformer. It is just a switch, setting `cluster_inter =1` will enable clustering within transformer, and `cluster_inter =0` for baseline.

**Comment by kang7734** [comment]
Thank you very much for your reply.

In addition, 40.8% of performance is currently the highest up to MSVD data set. Can I check what I set wrong and the performance is not working?

we have only changed the above mentioned content while it is currently on the CenterCLIP Github.

**Comment by mzhaoshuai** [comment]
Well, `40.8%` is not a normal number. Check whether your setting is consistent with the scripts in the repo.
Another different setting maybe the `batch_size`, I did not try with a batch size `16x4=64`. 

By the way, do you preprocess the video to make them have fps=3 and size 224x224?

**Comment by kang7734** [comment]
Oh i just input raw video.. isn't there any preprocessing function? i will try it with pre-processing and leave a reply.

Thank you so much for your interest in my problem.

**Comment by mzhaoshuai** [comment]
check https://github.com/mzhaoshuai/CenterCLIP/blob/main/preprocess/compress_video.py.

**Comment by kang7734** [comment]
Thank you for waiting!! The results came out well Thank you very much.

Once again, thank you so much for sharing such great research

**Comment by mzhaoshuai** [comment]
Close due to inactivity. Free free to re-open.
