### ISSUE TITLE
Questions about reproduction based on ViT-B/16

### ISSUE THREAD

**Issue by HanielF** [mzhaoshuai/CenterCLIP#2]
I notice that the training script of CenterClip on MSRVTT(1ka) dataset is based on ViT-B/32. But I want to train the model based on ViT-B/16, which will produce a higher R@1 (48.4).

I modified the training script and try to match the configuration with that reported on paper, while `R@1` of T2V and V2T only up to 45.8 and 46.5, which is much lower than 48.4 and 47.7.

I will upload the model training log and could you check it out to find out any problems?

**Comment by HanielF** [comment]
[centerclip_vitb16.txt](https://github.com/mzhaoshuai/CenterCLIP/files/8841319/centerclip_vitb16.txt)

**Comment by mzhaoshuai** [comment]
Hi, it seems that you train the model on `MSRVTT training-7K`

```
======================== Running training ========================
2022-06-02,12:08:19 | INFO | Rank 0 |   Num examples = 140200
2022-06-02,12:08:19 | INFO | Rank 0 |   Batch size = 16
2022-06-02,12:08:19 | INFO | Rank 0 |   Num steps = 5475
2022-06-02,12:08:19 | INFO | Rank 0 | 
======================== Running test ========================
2022-06-02,12:08:19 | INFO | Rank 0 |   Num examples = 1000
2022-06-02,12:08:19 | INFO | Rank 0 |   Batch size = 16
2022-06-02,12:08:19 | INFO | Rank 0 |   Num steps = 63
2022-06-02,12:08:19 | INFO | Rank 0 | 
======================== Running val ========================
2022-06-02,12:08:19 | INFO | Rank 0 |   Num examples = 1000
2022-06-02,12:08:19 | INFO | Rank 0 | Start training epoch 0
```

![image](https://user-images.githubusercontent.com/22476764/172104678-acbc7588-e0de-4a92-be4c-d28ede8b9252.png)

You got `+1% R@1` on T2V, no gain on V2T . I check your log, a small bug at
```

2022-06-02,12:07:28 | INFO | Rank 0 | [cluster] Creating cluster algorithm object in transformer blocks:
	 algorithm: kmediods++
	 block_id (start 1): 7
	 **cluster: 160 --> 160**
	 frames: 12 --> 4
	 cluster_embedding / cluster_frame_embedding / adaptive_cls: [0 / 0 / False]
	 split_size: 4
	 distance / pre_norm / distance norm_p: [euclidean / 0 / 2.0]
	 stop threshold / iter_limit: [1e-06 / 100]
	 spectral_graph / sigma / knn_k / spg / sign correct: [HeatKernel / 2.0 / 20 / 0 / 1]
	 mean_residual: False
2022-06-02,12:07:28 | INFO | Rank 0 | [cluster] Creating cluster algorithm object in transformer blocks...[DONE]
```
It should be `cluster: 196 --> 160`, but I check the code and find this will not affect the final result.
So I cannot answer why your V2T results is low when training on `MSR-VTT 7K`.
Could you please upload your params file `hparams_train.json` the code produced?

By the way, the setting for ViT-B16 on `MSR-VTT 9K` I used is
```
train_csv=${DATA_PATH}/MSRVTT_train.9k.csv
pretrained_clip_name=ViT-B/16
max_frames=12
max_words=32
lr=5e-3
coef_lr=1e-3
wd=0.2
optim=AdamW
cluster_inter=1
cluster_algo='kmediods++'
minkowski_norm_p=2.0
cluster_distance='euclidean'
cluster_num_blocks='196 196 196 196 196 196 160 160 160 160 160 160'
target_frames_blocks='12 12 12 12 12 12 4 4 4 4 4 4'
```
and I preprocess the videos to make them have `fps=3` and size `224`.

**Comment by HanielF** [comment]
Thanks for your help!
I forgot to change the `$train_csv` parameter before training the model. 
As for `$cluster_num_blocks`, the default in `msrvtt.sh` is `'49 49 49 49 49 49 49 49 49 49 49 49'`, and I changed it into `'160 160 160 160 160 160 160 160 160 160 160 160'`, which is an incorrect configuration.
I have fixed the configuration error and retrained it based on msrvtt-1ka. 
Thanks again~

**Comment by HanielF** [comment]
The params file `hparams_train.json` generated under the wrong configuration is uploaded as follows.
[hparams_train_7k.json.txt](https://github.com/mzhaoshuai/CenterCLIP/files/8842412/hparams_train_7k.json.txt)


And here is the `hparams_train.json` file produced by the currently trained model on msrvtt-1ka.
[hparams_train_9k.json.txt](https://github.com/mzhaoshuai/CenterCLIP/files/8842411/hparams_train_9k.json.txt)

**Comment by mzhaoshuai** [comment]
> The params file `hparams_train.json` generated under the wrong configuration is uploaded as follows. [hparams_train_7k.json.txt](https://github.com/mzhaoshuai/CenterCLIP/files/8842412/hparams_train_7k.json.txt)
> 
> And here is the `hparams_train.json` file produced by the currently trained model on msrvtt-1ka. [hparams_train_9k.json.txt](https://github.com/mzhaoshuai/CenterCLIP/files/8842411/hparams_train_9k.json.txt)

Thx for your work:+1:. I did not find anything wrong in [hparams_train_9k.json.txt](https://github.com/mzhaoshuai/CenterCLIP/files/8842411/hparams_train_9k.json.txt).
Hope you get a nice result.

**Comment by HanielF** [comment]
Thank you very much!
After the training is finished, I will update the results of the model.

**Comment by HanielF** [comment]
To obtain the highest R@1 of T2V, I select the checkpoint after the first epoch as the best one. And the result is `'T2V: R@1: 47.1 - R@5: 74.3 - R@10: 82.4 - Median R: 2.0 - Mean R: 13.7', 'V2T: R@1: 45.8 - R@5: 75.1 - R@10: 83.0 - Median R: 2.0 - Mean R: 10.4'`, which is much better than before.
Thanks for your help!
