### ISSUE TITLE
How to download ActivityNet?

### ISSUE THREAD

**Issue by weirukai** [mzhaoshuai/CenterCLIP#3]
I am honored to read your paper, CenterCLIP. How can I download the ActivityNet dataset? The source data provided on Baidu Drive by the official website has some problems when I try to unzip it.

**Comment by mzhaoshuai** [comment]
Well, I also download ActivityNet via the official link, but now it is expired. Is there anything like `md5sum`? Then you can check whether your downloaded zip file is corrupted. If it is corrupted, just send an email to the host of ActivityNet. I think they will be happy that someone helps them find some bugs.

**Comment by mzhaoshuai** [comment]
Feel free to re-open.

**Comment by Cola-any** [comment]
Hi, I noticed that there are two versions of the ActivityNet dataset, V1-2 and V1-3, which one should I download?
