### ISSUE TITLE
ActivityNet clip feature

### ISSUE THREAD

**Issue by gdg452** [mzhaoshuai/CenterCLIP#4]
Thank you so much for the fantastic code!
could you please share the ActivityNet dataset feature extracted by the image encoder of CLIP if you are convenient，I am a new researcher and want to do research in a similar direction. Thank you!

**Comment by mzhaoshuai** [comment]
Well, I move to a new place and I am afraid that I cannot provide such features now.

**Comment by gdg452** [comment]
Thank you for your reply!! I still appreciate your reply
